site_name: keepass-env
site_url: https://tandav.github.io/keepass-env
repo_url: https://github.com/tandav/keepass-env
repo_name: tandav/keepass-env
edit_uri: edit/master/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    logo: simple/keepassxc
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - navigation.instant
    - content.action.edit
    - content.action.view
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
