name: ci

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: install dependencies
        run: python3 -m pip install -e .[dev]

      - name: test
        run: pytest --cov keepass_env

      # - name: lint
      #   run: pre-commit run --all-files

  publish-to-pypi-and-github-release:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags')"
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pypa/build
        run: python -m pip install --upgrade setuptools build twine

      - name: Build a source tarball and wheel
        run: python -m build .

      - name: upload to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*

      - name: Github Release
        uses: softprops/action-gh-release@v1

  mkdocs-github-pages:
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
